### ISSUE TITLE
It is not possible to rescan an already scanned URL

### ISSUE THREAD

**Issue by juananpe** [whatwebgui/WhatWebGUI#10]
Right now It is not possible to rescan an already scanned URL. This is a critical feature IMHO and should be fixed.
![image](https://user-images.githubusercontent.com/1078305/104134608-025ad980-538b-11eb-8050-c21dee7722a8.png)

I know for sure that with the new "aggressive mode" in settings, the Joomla plugin will recognize the exact version of the URL in the provided image...

PD: please add some tags like "New feature", "Enhancement", "Bug", "Wontfix", etc. to the project, so we can tag the issues properly

**Comment by adeiarias** [comment]
Done
We have upload the code to github
